# Generated by Django 5.1.1 on 2024-10-14 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='coordenada_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='coordenada_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='hash_documento',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firma',
            name='documento',
            field=models.FileField(upload_to='documentos_firmados/'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='fecha_firma',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firma_valida',
            field=models.BooleanField(default=True),
        ),
    ]
